export const LOGIN_PENDING = "LOGIN_PENDING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_REJECTED = "LOGIN_REJECTED";

export const FORGET_PASS_PENDING = "FORGET_PASS_PENDING";
export const FORGET_PASS_SUCCESS = "FORGET_PASS_SUCCESS";
export const FORGET_PASS_REJECTED = "FORGET_PASS_REJECTED";

export const RESET_AUTH_STATE = "RESET_AUTH_STATE";
